Algoritmo "Meu primeiro algoritimo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Eu mesmo com Claiton da estia
// Descrição   : Só ensina  (função)
// Autor(a)    : Plinio Camilo P Santos
// Data atual  : 13/07/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreval ("resultado:", nota)
   

Fimalgoritmo